S = " have a nice DAY  "
print (S) 
print (S.upper() )
print (S.lower() )
print (S.capitalize() )
print (S.title() )
print (S.swapcase() )
print (S.strip() )
print (S.center(50) )
print (S.center(50,'@'))
print (S.replace('nice','good'))
print (S.find('DAY'))
print (S.find('a'))
print (S.count('A'))
print (S.count('e'))
print (S.join('@#$'))
print (S.startswith('h'))
print (S.endswith('Y'))
print ('123'.zfill(5))
print (S.split())
print (dir(S)) 


